### PR TITLE
Normalize scoped names in build

### PR DESCRIPTION
**Pull request by d0whc3r**
PR for https://github.com/kazupon/vue-cli-plugin-p11n/issues/10 issue

### CODE REVIEW

**Comment by EvanBurbidge** [comment]
@d0whc3r  update the stripNamespaceIfExists method to this 

```javascript
function stripNamespaceIfExists (name) {
  if (!name) return;
  if (name.indexOf('@') === -1) return name;
  return name.split('/').slice(-1).join('');
}
```

otherwise you'll have a failing test case on commands/build.spec.js

**Comment by d0whc3r** [comment]
@kazupon I see you have circleCi but there is no checks for pull requests, maybe you have to enable it?

**Comment by kazupon** [comment]
@d0whc3r 
Sorry, I had mistaked circle CI configuration.
Update done.

**Comment by d0whc3r** [comment]
Ok, I removed semicolons but lint doesn't show me any error

```bash
$ yarn lint
yarn run v1.12.3
$ eslint --fix --ext .js .
Done in 2.30s.
```

**Pull request merged**
